"""raw records and provenance

Revision ID: 0003
Revises: 0002
Create Date: 2026-07-18 22:45:53.993010

"""

from collections.abc import Sequence

import sqlalchemy as sa  # noqa: F401  (kept for consistency across migrations)
from alembic import op  # noqa: F401  (kept for consistency across migrations)

# revision identifiers, used by Alembic.
revision: str = "0003"
down_revision: str | Sequence[str] | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "raw_records",
        sa.Column("raw_record_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("external_id", sa.String(), nullable=True),
        sa.Column("content_type", sa.String(), nullable=False),
        sa.Column("content", sa.JSON(), nullable=False),
        sa.Column("checksum", sa.String(), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("correlation_id", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("raw_record_id"),
        sa.UniqueConstraint("source", "checksum", name="uq_raw_records_source_checksum"),
    )
    op.create_index(
        "ix_raw_records_source_external", "raw_records", ["source", "external_id"], unique=False
    )
    op.create_index(op.f("ix_raw_records_user_id"), "raw_records", ["user_id"], unique=False)
    op.add_column("events", sa.Column("raw_record_id", sa.Uuid(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("events", "raw_record_id")
    op.drop_index(op.f("ix_raw_records_user_id"), table_name="raw_records")
    op.drop_index("ix_raw_records_source_external", table_name="raw_records")
    op.drop_table("raw_records")
    # ### end Alembic commands ###
