"""event correction

Revision ID: 0004
Revises: 0003
Create Date: 2026-07-18 22:53:06.361787

"""

from collections.abc import Sequence

import sqlalchemy as sa  # noqa: F401  (kept for consistency across migrations)
from alembic import op  # noqa: F401  (kept for consistency across migrations)

# revision identifiers, used by Alembic.
revision: str = "0004"
down_revision: str | Sequence[str] | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("events", sa.Column("corrects_event_id", sa.Uuid(), nullable=True))
    op.create_index("ix_events_corrects_event_id", "events", ["corrects_event_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_events_corrects_event_id", table_name="events")
    op.drop_column("events", "corrects_event_id")
    # ### end Alembic commands ###
