"""entities and relationships

Revision ID: 0005
Revises: 0004
Create Date: 2026-07-18 23:53:11.086080

"""

from collections.abc import Sequence

import sqlalchemy as sa  # noqa: F401  (kept for consistency across migrations)
from alembic import op  # noqa: F401  (kept for consistency across migrations)

# revision identifiers, used by Alembic.
revision: str = "0005"
down_revision: str | Sequence[str] | None = "0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "entities",
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("entity_type", sa.String(), nullable=False),
        sa.Column("entity_key", sa.String(), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("occurrences", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("entity_id"),
        sa.UniqueConstraint(
            "user_id", "entity_type", "entity_key", name="uq_entities_user_type_key"
        ),
    )
    op.create_index(op.f("ix_entities_user_id"), "entities", ["user_id"], unique=False)
    op.create_table(
        "relationships",
        sa.Column("relationship_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("source_entity_id", sa.Uuid(), nullable=False),
        sa.Column("target_entity_id", sa.Uuid(), nullable=False),
        sa.Column("rel_type", sa.String(), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("occurrences", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("relationship_id"),
        sa.UniqueConstraint(
            "user_id",
            "source_entity_id",
            "target_entity_id",
            "rel_type",
            name="uq_relationships_edge",
        ),
    )
    op.create_index(op.f("ix_relationships_user_id"), "relationships", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_relationships_user_id"), table_name="relationships")
    op.drop_table("relationships")
    op.drop_index(op.f("ix_entities_user_id"), table_name="entities")
    op.drop_table("entities")
    # ### end Alembic commands ###
