"""forecast_outcomes

Revision ID: 0018
Revises: 0017
Create Date: 2026-07-19 18:05:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa  # noqa: F401  (kept for consistency across migrations)
from alembic import op  # noqa: F401  (kept for consistency across migrations)

# revision identifiers, used by Alembic.
revision: str = "0018"
down_revision: str | Sequence[str] | None = "0017"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "forecast_outcomes",
        sa.Column("outcome_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("forecast_id", sa.Uuid(), nullable=False),
        sa.Column("observed_value", sa.Integer(), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("note", sa.String(), nullable=True),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("outcome_id"),
    )
    op.create_index(
        op.f("ix_forecast_outcomes_user_id"), "forecast_outcomes", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_forecast_outcomes_forecast_id"),
        "forecast_outcomes",
        ["forecast_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_forecast_outcomes_forecast_id"), table_name="forecast_outcomes")
    op.drop_index(op.f("ix_forecast_outcomes_user_id"), table_name="forecast_outcomes")
    op.drop_table("forecast_outcomes")
    # ### end Alembic commands ###
