"""bills

Revision ID: 0019
Revises: 0018
Create Date: 2026-09-21 22:00:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa  # noqa: F401  (kept for consistency across migrations)
from alembic import op  # noqa: F401  (kept for consistency across migrations)

# revision identifiers, used by Alembic.
revision: str = "0019"
down_revision: str | Sequence[str] | None = "0018"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bills",
        sa.Column("bill_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("payee", sa.String(), nullable=False),
        sa.Column("amount_minor", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(), nullable=False),
        sa.Column("category", sa.String(), nullable=True),
        sa.Column("recurrence", sa.String(), nullable=False),
        sa.Column("due_day", sa.Integer(), nullable=True),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("bill_id"),
    )
    op.create_index(op.f("ix_bills_user_id"), "bills", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_bills_user_id"), table_name="bills")
    op.drop_table("bills")
    # ### end Alembic commands ###
